DROP TABLE IF EXISTS Account;
CREATE TABLE IF NOT EXISTS Account(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  salt TEXT NOT NULL
);
DROP TABLE IF EXISTS Sessions;
CREATE TABLE IF NOT EXISTS Sessions(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  session TEXT NOT NULL,
  expire DATE DEFAULT (DATETIME('now','+7 day'))
);
DROP TABLE IF EXISTS ReadHistory;
CREATE TABLE IF NOT EXISTS ReadHistory(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  bookid TEXT NOT NULL,
  text INTEGER DEFAULT 0
);
CREATE UNIQUE INDEX idx_ReadHistory ON ReadHistory (username, bookid);